# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import oauth2_provider.validators


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_application', '0004_auto_20170901_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='description',
        ),
        migrations.AlterField(
            model_name='application',
            name='url',
            field=models.TextField(blank=True, validators=[oauth2_provider.validators.validate_uris]),
        ),
    ]
