# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import oauth2_provider.validators


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_application', '0008_auto_20170901_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Show it in website'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='url',
            field=models.CharField(max_length=200, validators=[oauth2_provider.validators.validate_uris], verbose_name='url'),
        ),
    ]
