# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 11:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0002_auto_20170829_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='user_upd',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bookmark_user_upd', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tag',
            name='user_upd',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tag_user_upd', to=settings.AUTH_USER_MODEL),
        ),
    ]
